include:
  - template: Security/SAST.gitlab-ci.yml

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == 'master'

stages:
  - build
  - test
  - sast-test

variables:
  SAST_EXCLUDED_PATHS: "target, node_modules, .git"

build-job:
  stage: build
  image: eclipse-temurin:25-jdk
  cache:
    key: "$CI_COMMIT_REF_SLUG" #имя кэша
    paths: #что именно сохраняем в кэш
      - backend/.m2/repository/
    policy: push
  before_script:
    - cd backend
  script:
    - ./mvnw package -B -DskipTests=true -Djacoco.skip=true
  artifacts:
    paths:
      - backend/target/
    expire_in: 25 minutes

test-job:
  stage: test
  image: eclipse-temurin:25-jdk
  needs:
    - build-job
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - backend/.m2/repository/
    policy: pull
  before_script:
    - cd backend
  script:
    - ./mvnw test -B

sast:
  stage: sast-test
  needs:
      - job: build-job
        artifacts: true
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - backend/.m2/repository/
    policy: pull
  variables:
    COMPILE: "false"
    MAVEN_REPO_PATH: ${CI_PROJECT_DIR}/backend/.m2/repository

